<br>
<br>
<p>Framework simples e puro para desenvolvedores raiz.</p>

<div class="shadow-sm p-3 mb-5 bg-white rounded">
    <p>Desenvolvido por:</p>
    <ul class="list-unstyled">
        <li class="media">
            <img src="imagens/bruno.jpg" class="mr-3" alt="...">
            <div class="media-body">
            <h5 class="mt-0 mb-1">Bruno Duarte</h5>
                <p>24 anos, Apaixodo por desenvolvimento web e mobile, Mestrando em Engenharia de Software.</p>
                <a href="https://instagram.com/brunoduarth" target="_blank" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Instagram</a>
            </div>
        </li>
    </ul>
</div>